// Code generated by "stringer -output stringers.go -type Event"; DO NOT EDIT.

package authboss

import "strconv"

const _Event_name = "EventRegisterEventAuthEventAuthFailEventRecoverStartEventRecoverEndEventGetUserEventGetUserSessionEventPasswordResetEventLogout"

var _Event_index = [...]uint8{0, 13, 22, 35, 52, 67, 79, 98, 116, 127}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
